base_path: "/home/aroman/repos/act_gal_ksz_pipe/cluster_scripts/"
tmp_dir: "/home/aroman/repos/act_gal_ksz_pipe/tmp/"
scripts:
  make-cl-tz.py:
    base_path: "make-cl-tz/"
    NTRIAL_MC: 0
    NTRIAL_TT: 4
    LMAX: 10000
    L_KSZ_SUM: 2000
    plots: True
    data_path: "/home/aroman/data/"
    planck_mask_path: "/home/aroman/data/mask/planck_foreground_mask_GAL080.npy"
    freq: 90
    freq_string: "090"
    map_path: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_AA_f090_daynight_map_srcfree.fits"
    ivar_path: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_AA_f090_daynight_ivar.fits"
    beam_path: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_f090_daynight_beam.txt"
    map_weight_path: "/home/aroman/data/kendrick/01_act_ps_model_inputs/wfkp_90.fits"
    # gal_mask_path: "/home/aroman/data/vr_source/desils/intersect_sdss_desi_mask.fits"
    gal_mask_path: "/home/aroman/data/kendrick/01_act_ps_model_inputs/desils_sdss_footprint_ds20.fits"
    gal_upgrade: 20
    desils_v3_north: "/home/aroman/data/vr_source/desils/v03_desils_north_cmass.h5"
    desils_v3_south: "/home/aroman/data/vr_source/desils/v03_desils_south_cmass.h5"
    vr_width: '1.0'
    zerr_max: 0.0225
    do_cut: True

    do_cltz_rand: False
    rand_cat_path: "/home/aroman/data/kendrick/02_pixellized_lss_maps/random_catalog.h5"

    do_vmean_sub: True

    # cl_tt_sim_path: "/gpfs/aroman/data/desils/cl_tt_kendrick_data_f090_ntrial_4.npy"
    cl_tt_sim_path: "/home/aroman/data/desils/cl_tt_sim_kendrick_data_f090.npz"
    cl_tt_act_path: "/home/aroman/data/desils/cl_tt_act_kendrick_data_f090.npy"
    cl_tz_mc_path: "/home/aroman/data/desils/cl_tz_mc_kendrick_data_vmeansub_f090_nmc_1024.npy"
    cl_tz_sig_path: "/home/aroman/data/desils/cl_tz_sig_kendrick_data_vmeansub_f090.npy"
    fl_sim_path: "/home/aroman/data/desils/fl_apparent_camb_f090.npy"
    cl_model: [0.00001, -4, 0.93]
    cmb_path: '/home/aroman/data/kendrick/01_act_ps_model_inputs/cl_camb.npy'