base_path: "/home/aroman/ksz_repos/act_gal_ksz_pipe/"
tmp_dir: "/home/aroman/ksz_repos/act_gal_ksz_pipe/tmp/"
scripts:
  explore-multifreq-bootstrap.py:
    base_path: "scripts/"
    NTRIAL_NL: 1024
    NTRIAL_FL: 32
    NAVE_FL: 60
    NITER_FL: 40
    NTRIAL_MC: 0
    plots: True
    data_path: "/home/aroman/data/"
    planck_enmap_path: "/home/aroman/data/mask/planck_foreground.npy"
    map_90: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_AA_f090_daynight_map_srcfree.fits"
    ivar_90: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_AA_f090_daynight_ivar.fits"
    beam_90: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_f090_daynight_beam.txt"
    map_150: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_AA_f150_daynight_map_srcfree.fits"
    ivar_150: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_AA_f150_daynight_ivar.fits"
    beam_150: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_f150_daynight_beam.txt"
    map_220: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_AA_f220_daynight_map_srcfree.fits"
    ivar_220: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_AA_f220_daynight_ivar.fits"
    beam_220: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_f220_daynight_beam.txt"
    # nl_path: "/data/aroman/symmetry/desils/nl_desils_pub_4096.npy"
    # fl_path: "/data/aroman/symmetry/desils/fl_desils_pub_nfl_32_nave_60_niter_40.npy"
    gal_mask_path: "/home/aroman/data/vr_source/desils/intersect_sdss_desi_mask.fits"
    desils_v3_north: "/home/aroman/data/vr_source/desils/v03_desils_north_cmass.h5"
    desils_v3_south: "/home/aroman/data/vr_source/desils/v03_desils_south_cmass.h5"
    vr_width: '1.0'
    zerr_max: 0.0225
    do_cut: True