base_path: "/home/aroman/ksz_repos/act_gal_ksz_pipe/"
tmp_dir: "/home/aroman/ksz_repos/act_gal_ksz_pipe/tmp/"
scripts:
  plot-cl-tz.py:
    base_path: "scripts/"
    cl_tt_act_path: "/data/aroman/symmetry/desils/cl_tt_act_kendrick_data_f090.npy"
    cl_tt_sim_path: "/data/aroman/symmetry/desils/cl_tt_sim_kendrick_data_f090.npz"
    # cl_tz_mc_path: "/data/aroman/symmetry/desils/cl_tz_mc_kendrick_data_f090_nmc_1024.npy"
    # cl_tz_sig_path: "/data/aroman/symmetry/desils/cl_tz_sig_kendrick_data_f090.npy"
    cl_tz_mc_path: "/data/aroman/symmetry/desils/cl_tz_mc_kendrick_data_vmeansub_f090_nmc_1024.npy"
    cl_tz_sig_path: "/data/aroman/symmetry/desils/cl_tz_sig_kendrick_data_vmeansub_f090.npy"
    fl_sim_path: "/data/aroman/symmetry/desils/fl_apparent_camb_f090.npy"
    NAVE_TZ_L: 500
    NAVE_TT: 64
    LMIN_PLOT: 501
    ifit_min: 4
    ifit_max: 14
    LREF: 8000
    confidence: 0.6827

    zerr_max: 0.0225
    do_cut: True
    vr_width: "1.0"
    freq: 90
    freq_str: "f090"
    cl_tz_scale: 1.3538

    # planck_mask_path: "/home/aroman/data/mask/planck_foreground_mask_GAL080.npy"
    # map_path: "/home/aroman/data/act_pub/act_dr5.01_s08s18_AA_f090_daynight_map_srcfree.fits"
    # ivar_path: "/home/aroman/data/act_pub/act_dr5.01_s08s18_AA_f090_daynight_ivar.fits"
    map_weight_path: "/home/aroman/data/kendrick/01_act_ps_model_inputs/wfkp_90.fits"
    beam_path: "/home/aroman/data/act_pub/act_planck_dr5.01_s08s18_f090_daynight_beam.txt"
    # nl_path: "/data/aroman/symmetry/desils/nl_desils_pub_actonly_newfkp_cltz_f090_1024.npy"
    # fl_path: "/data/aroman/symmetry/desils/fl_desils_pub_actonly_newfkp_cltz_f090_nfl_32_nave_60_niter_1.npy"
    # gal_mask_path: "/home/aroman/data/vr_source/desils/intersect_sdss_desi_mask.fits"
    # desils_v3_north: "/home/aroman/data/vr_source/desils/v03_desils_north_cmass.h5"
    # desils_v3_south: "/home/aroman/data/vr_source/desils/v03_desils_south_cmass.h5"